version: '3'
services:
    web:
        build:
            context: .
            args:
                - APP_ENV=production
        expose:
            - 8000
        environment:
            - PYTHONUNBUFFERED=1
        volumes:
            - .:/src
        depends_on:
            - db
            - mqtt
        command: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:8000 'app:create_app(config_name="production")'
    
    db:
        image: mysql/mysql-server:8.0
        restart: always
        env_file:
            - ./database/secret.env
        volumes:
            - mysql_volume:/var/lib/mysql
            - ./database/sqls:/docker-entrypoint-initdb.d
        command: ['--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    
    mqtt:
        image: eclipse-mosquitto
        ports:
            - 1883:1883
        restart: unless-stopped
    
    mqtt-client:
        build:
            context: .
            args:
                REQ_TXT: requirements.mqtt-client.txt
        environment:
            - PYTHONUNBUFFERED=1
        volumes:
            - .:/src
        depends_on:
            - mqtt
        command: python3 run_mqtt_client.py

    nginx:
        image: nginx:1.18
        volumes:
             - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - web

volumes:
    mysql_volume: