"""Add Tables

Revision ID: 2ded8f41db80
Revises: 08219a3df140
Create Date: 2020-12-15 16:51:27.568202

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ded8f41db80'
down_revision = '08219a3df140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anchorwaypoint',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('globalx', sa.DECIMAL(precision=11, scale=9), nullable=True),
    sa.Column('globaly', sa.DECIMAL(precision=12, scale=9), nullable=True),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_table('ranchors',
    sa.Column('raid', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('aid1', sa.Integer(), nullable=True),
    sa.Column('aid2', sa.Integer(), nullable=True),
    sa.Column('edge', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('raid')
    )
    op.create_table('rvehmis',
    sa.Column('rvmid', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('vid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('rvmid')
    )
    op.create_table('rvehstateencounter',
    sa.Column('rvseid', sa.Integer(), nullable=False),
    sa.Column('vsid', sa.Integer(), nullable=True),
    sa.Column('vsid2', sa.Integer(), nullable=True),
    sa.Column('commtype', sa.String(length=8), nullable=True),
    sa.Column('range', sa.Float(), nullable=True),
    sa.Column('rssi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('rvseid')
    )
    op.create_table('vehstate',
    sa.Column('vsid', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('vid', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('powerlevel', sa.Integer(), nullable=True),
    sa.Column('tempcpu', sa.Float(), nullable=True),
    sa.Column('tempenv', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('vsid')
    )
    op.create_table('vehstatsanchor',
    sa.Column('vsaid', sa.Integer(), nullable=False),
    sa.Column('vsid', sa.Integer(), nullable=True),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.Column('commtype', sa.String(length=8), nullable=True),
    sa.Column('range', sa.Float(), nullable=True),
    sa.Column('rssi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('vsaid')
    )
    op.add_column('mission', sa.Column('endtime', sa.DateTime(), nullable=True))
    op.add_column('mission', sa.Column('starttime', sa.DateTime(), nullable=True))
    op.drop_index('mid', table_name='mission')
    op.drop_column('mission', 'id')
    op.drop_index('vid', table_name='vehicle')
    op.drop_column('vehicle', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('vid', 'vehicle', ['vid'], unique=True)
    op.add_column('mission', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('mid', 'mission', ['mid'], unique=True)
    op.drop_column('mission', 'starttime')
    op.drop_column('mission', 'endtime')
    op.drop_table('vehstatsanchor')
    op.drop_table('vehstate')
    op.drop_table('rvehstateencounter')
    op.drop_table('rvehmis')
    op.drop_table('ranchors')
    op.drop_table('anchorwaypoint')
    # ### end Alembic commands ###
