"""Rename Tables

Revision ID: 5b595d537279
Revises: d5261d0cf759
Create Date: 2020-12-29 18:19:23.361356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b595d537279'
down_revision = 'd5261d0cf759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anchor_waypoint',
    sa.Column('aid', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('globalx', sa.DECIMAL(precision=11, scale=9), nullable=True),
    sa.Column('globaly', sa.DECIMAL(precision=12, scale=9), nullable=True),
    sa.Column('uwbid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('aid')
    )
    op.create_table('r_anchors',
    sa.Column('raid', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('aid1', sa.Integer(), nullable=True),
    sa.Column('aid2', sa.Integer(), nullable=True),
    sa.Column('edge', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('raid')
    )
    op.create_table('r_veh_mis',
    sa.Column('rvmid', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('vid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('rvmid')
    )
    op.create_table('r_vehstate_encounter',
    sa.Column('rvseid', sa.Integer(), nullable=False),
    sa.Column('vsid', sa.Integer(), nullable=True),
    sa.Column('vsid2', sa.Integer(), nullable=True),
    sa.Column('commtypeid', sa.Integer(), nullable=True),
    sa.Column('range', sa.Float(), nullable=True),
    sa.Column('rssi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('rvseid')
    )
    op.create_table('vehstats_anchor',
    sa.Column('vsaid', sa.Integer(), nullable=False),
    sa.Column('vsid', sa.Integer(), nullable=True),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.Column('commtypeid', sa.Integer(), nullable=True),
    sa.Column('range', sa.Float(), nullable=True),
    sa.Column('rssi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('vsaid')
    )
    op.drop_table('rvehmis')
    op.drop_table('rvehstateencounter')
    op.drop_table('anchorwaypoint')
    op.drop_table('vehstatsanchor')
    op.drop_table('ranchors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranchors',
    sa.Column('raid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aid1', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aid2', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('edge', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('raid'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vehstatsanchor',
    sa.Column('vsaid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vsid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('range', mysql.FLOAT(), nullable=True),
    sa.Column('rssi', mysql.FLOAT(), nullable=True),
    sa.Column('commtypeid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('vsaid'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('anchorwaypoint',
    sa.Column('aid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('globalx', mysql.DECIMAL(precision=11, scale=9), nullable=True),
    sa.Column('globaly', mysql.DECIMAL(precision=12, scale=9), nullable=True),
    sa.Column('uwbid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('aid'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rvehstateencounter',
    sa.Column('rvseid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vsid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vsid2', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('range', mysql.FLOAT(), nullable=True),
    sa.Column('rssi', mysql.FLOAT(), nullable=True),
    sa.Column('commtypeid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('rvseid'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rvehmis',
    sa.Column('rvmid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('rvmid'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('vehstats_anchor')
    op.drop_table('r_vehstate_encounter')
    op.drop_table('r_veh_mis')
    op.drop_table('r_anchors')
    op.drop_table('anchor_waypoint')
    # ### end Alembic commands ###
