"""Add Table MqttRecord

Revision ID: 5e62b4aaef46
Revises: 5b595d537279
Create Date: 2021-01-03 16:50:59.947563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e62b4aaef46'
down_revision = '5b595d537279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mqtt_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=32), nullable=True),
    sa.Column('message', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mqtt_record')
    # ### end Alembic commands ###
