"""remove RuwbVeh

Revision ID: 75c2cb26c5f2
Revises: c5bc2e3d4b9c
Create Date: 2021-02-02 19:06:34.534366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75c2cb26c5f2'
down_revision = 'c5bc2e3d4b9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('r_uwb_veh')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('r_uwb_veh',
    sa.Column('vid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uwbid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loc', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=32), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('mid', mysql.INTEGER(), autoincrement=False, nullable=False),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
