"""Mission add updated_at

Revision ID: 8f536264eca3
Revises: e26f44059ad8
Create Date: 2021-02-11 01:21:22.601006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f536264eca3'
down_revision = 'e26f44059ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mission', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mission', 'updated_at')
    # ### end Alembic commands ###
