"""Rename MqttRecord.message to payload

Revision ID: b491c2ba66a1
Revises: 5e62b4aaef46
Create Date: 2021-01-03 18:13:27.372962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b491c2ba66a1'
down_revision = '5e62b4aaef46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mqtt_record', sa.Column('payload', sa.String(length=128), nullable=True))
    op.drop_column('mqtt_record', 'message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mqtt_record', sa.Column('message', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True))
    op.drop_column('mqtt_record', 'payload')
    # ### end Alembic commands ###
