"""All tables add created_at

Revision ID: c5bc2e3d4b9c
Revises: b491c2ba66a1
Create Date: 2021-01-27 15:39:38.499202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5bc2e3d4b9c'
down_revision = 'b491c2ba66a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anchor_waypoint', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('commtype', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('mission', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('r_anchors', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('r_uwb_veh', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('r_veh_mis', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('r_vehstate_encounter', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('uwb_module', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('vehicle', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('vehstate', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('vehstats_anchor', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehstats_anchor', 'created_at')
    op.drop_column('vehstate', 'created_at')
    op.drop_column('vehicle', 'created_at')
    op.drop_column('uwb_module', 'created_at')
    op.drop_column('r_vehstate_encounter', 'created_at')
    op.drop_column('r_veh_mis', 'created_at')
    op.drop_column('r_uwb_veh', 'created_at')
    op.drop_column('r_anchors', 'created_at')
    op.drop_column('mission', 'created_at')
    op.drop_column('commtype', 'created_at')
    op.drop_column('anchor_waypoint', 'created_at')
    # ### end Alembic commands ###
