"""add RuwbVeh back

Revision ID: d4e132c84d0b
Revises: 75c2cb26c5f2
Create Date: 2021-02-02 19:07:12.766842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4e132c84d0b'
down_revision = '75c2cb26c5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('r_uwb_veh',
    sa.Column('ruvid', sa.Integer(), nullable=False),
    sa.Column('vid', sa.Integer(), nullable=True),
    sa.Column('uwbid', sa.Integer(), nullable=True),
    sa.Column('loc', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ruvid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('r_uwb_veh')
    # ### end Alembic commands ###
