"""Add Table RUwbVeh, CommType

Revision ID: d5261d0cf759
Revises: 4359f5b04eea
Create Date: 2020-12-29 18:14:05.317149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5261d0cf759'
down_revision = '4359f5b04eea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commtype',
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('cid')
    )
    op.create_table('r_uwb_veh',
    sa.Column('mid', sa.Integer(), nullable=False),
    sa.Column('vid', sa.Integer(), nullable=True),
    sa.Column('uwbid', sa.Integer(), nullable=True),
    sa.Column('loc', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('mid')
    )
    op.create_table('uwb_module',
    sa.Column('uwbid', sa.Integer(), nullable=False),
    sa.Column('address', sa.Binary(), nullable=True),
    sa.Column('serial', sa.Binary(), nullable=True),
    sa.PrimaryKeyConstraint('uwbid')
    )
    op.drop_table('uwbmodule')
    op.add_column('rvehstateencounter', sa.Column('commtypeid', sa.Integer(), nullable=True))
    op.drop_column('rvehstateencounter', 'commtype')
    op.add_column('vehstatsanchor', sa.Column('commtypeid', sa.Integer(), nullable=True))
    op.drop_column('vehstatsanchor', 'commtype')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehstatsanchor', sa.Column('commtype', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8), nullable=True))
    op.drop_column('vehstatsanchor', 'commtypeid')
    op.add_column('rvehstateencounter', sa.Column('commtype', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=8), nullable=True))
    op.drop_column('rvehstateencounter', 'commtypeid')
    op.create_table('uwbmodule',
    sa.Column('uwbid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('address', sa.BLOB(), nullable=True),
    sa.Column('serial', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('uwbid'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('uwb_module')
    op.drop_table('r_uwb_veh')
    op.drop_table('commtype')
    # ### end Alembic commands ###
