"""VehState add gloablx, globaly

Revision ID: e26f44059ad8
Revises: d4e132c84d0b
Create Date: 2021-02-10 22:06:50.383116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e26f44059ad8'
down_revision = 'd4e132c84d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehstate', sa.Column('globalx', sa.DECIMAL(precision=11, scale=9), nullable=True))
    op.add_column('vehstate', sa.Column('globaly', sa.DECIMAL(precision=12, scale=9), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehstate', 'globaly')
    op.drop_column('vehstate', 'globalx')
    # ### end Alembic commands ###
