name: Python Linter

on:
  push:
    branches: [ main ]

jobs:
  lint-codebase:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Lint Code Base
      uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        failIf: any
        args: "--exclude=migrations/,instance/ ."