name: Python Linter

on:
  push:
    branches: [ main ]

jobs:
  lint-codebase:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Lint Code Base
      uses: github/super-linter@v3
      env:
        VALIDATE_PYTHON_FLAKE8: true
        DEFAULT_BRANCH: main