name: Python Linter

on:
  push:
    branches: [ main ]

jobs:
  lint-codebase:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Lint Code Base
      uses: ricardochaves/python-lint@v1.3.0
      with:
        use-pylint: false
        use-pycodestyle: false
        use-flake8: true
        use-black: false
        use-mypy: false
        use-isort: false
        extra-flake8-options: "--exclude=migrations/,instance/"